### ISSUE TITLE
jQuery and ES6 questions

### ISSUE THREAD

**Issue by dariocravero** [openannotation/xpath-range#10]
Hi all,

I hope you're well :).

I was wondering if you would consider PRs with:
- vanilla JS instead of jQuery, and
- ES6/7 instead of coffee code.

Thanks :)

**Comment by tilgovi** [comment]
Yes!

**Comment by tilgovi** [comment]
I'd prefer one at a time :)

**Comment by tilgovi** [comment]
I've just released a few ES6 libs myself. Please let me know what you think about my packaging. I'd love to learn from whatever you've been doing. https://github.com/hypothesis/dom-anchor-text-position

**Comment by dariocravero** [comment]
Great @tilgovi! :) Will try to push some stuff soon. I agree it would be good to have them one at a time ;). Here's what I'm generally doing https://github.com/UXtemple/panels-runtime https://github.com/UXtemple/panels-blocks :).

**Comment by tilgovi** [comment]
PRs welcome :)

**Comment by tilgovi** [comment]
This is done. jQuery is gone and everything is converted to ES6.

**Comment by dariocravero** [comment]
Woohoo :) Amazing work! Thanks a mill!

**Comment by tilgovi** [comment]
I'll write up some history notes, but a lot of functionality has also been removed and I've settled on a very minimal API for the next release.

In particular, you'll want webmodules/range-normalize if you need to normalize range boundaries to the nearest leaf node and tilgovi/range-limit if you want to limit a range to a bounding node. I'm going to release a range-split-text (or similarly named module) later today.

**Comment by tilgovi** [comment]
And Annotator still needs the ability to iterate over the nodes in a range.
