### ISSUE TITLE
IE8: No such interface supported

### ISSUE THREAD

**Issue by krues8dr** [openannotation/xpath-range#3]
Per https://github.com/openannotation/annotator/issues/428 it looks like [the definition for `contains`](https://github.com/openannotation/xpath-range/blob/master/src/range.coffee#L381) doesn't work in IE8 as-is.  I'm not very familiar with this code, but this looks really similar to [Jquery#9815](http://bugs.jquery.com/ticket/9815) ?   For context, this is being generated by the unit tests.

**Comment by tilgovi** [comment]
Closed by #7 I think.
