### ISSUE TITLE
IE8: selection methods not available.

### ISSUE THREAD

**Issue by krues8dr** [openannotation/xpath-range#4]
In IE8, things like `document.createRange` and `window.getSelection` don't exist.  Per the discussion over on Annotator https://github.com/openannotation/annotator/pull/412#issuecomment-52648806 we're suggesting users use the Rangy plugin to fill these gaps - but that doesn't polyfill `window` or `document`, it just provides a standard interface instead a la jQuery.  

For instances like [this](https://github.com/openannotation/xpath-range/blob/master/src/range.coffee#L281) and [this](https://github.com/openannotation/xpath-range/blob/master/src/util.coffee#L90) I think it would make sense to test if rangy is being used and if not, default to the current methods.  E.g.:

    win = rangy ? Util.getGlobal()
    sel = win.getSelection() # Get the browser selection object

Relates to https://github.com/openannotation/annotator/issues/428

**Comment by tilgovi** [comment]
It sounds like this was resolved. Please re-open if that isn't so.
