### ISSUE TITLE
IE8: 'XPathResult' is undefined

### ISSUE THREAD

**Issue by krues8dr** [openannotation/xpath-range#5]
Going back to https://github.com/openannotation/annotator/issues/173, there's no support for XPath related operations in any version of IE really, so we'll need a shim here.  [`Wicked-Good-Xpath`](https://code.google.com/p/wicked-good-xpath/) does in fact solve most of the issues here, so I recommend adding that as part of the main package, since it affects even modern IEs.

**Comment by tilgovi** [comment]
As of 3046fc5f45a33dbe4a6f49d75901daeda466c66a we shouldn't have a strict dependency on XPath being available for our simple expressions.

**Comment by tilgovi** [comment]
IE8 is now passing all the tests here with rangy and wgxpath.
